"""Ecosystem exporters for Lope (v0.7 phase 8).

Three exporters live here:

* :func:`export_agtx_task` — turns a sprint doc, deliberation report,
  or any markdown body into an AGTX-shaped task spec. Pure, deterministic
  text transformation; no AGTX dependency required at runtime, no
  network call, no shellout.
* :func:`export_markdown_pr` and :func:`export_sarif` are thin
  wrappers around the Phase 3 review renderers so callers can address
  exports through one consistent module instead of stitching together
  ``lope.review`` and ``lope.sarif`` themselves.

Stdlib only. Every text path runs through :func:`lope.redaction.redact_text`
so a leaked credential never reaches a generated artifact.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from . import __version__ as _LOPE_VERSION
from .redaction import redact_text


# ---------------------------------------------------------------------------
# AGTX task spec
# ---------------------------------------------------------------------------


_DEFAULT_VALIDATION_COMMAND = "lope review <target> --consensus"

# The shape below is the contract advertised in the v0.7 sprint. AGTX is
# a separate project; this exporter only emits markdown, never imports
# AGTX, and never runs anything inside AGTX.
_AGTX_SECTION_ORDER = (
    "Source",
    "Objective",
    "Phases",
    "Acceptance Criteria",
    "Suggested Plugin",
    "Lope Validation Requirements",
)


@dataclass
class AgtxTask:
    """Materialized AGTX task spec, with its source content snapshot."""

    title: str
    body: str  # the rendered markdown
    source_label: str
    validation_command: str
    suggested_plugin: str

    def to_dict(self) -> Dict[str, str]:
        return {
            "title": self.title,
            "source_label": self.source_label,
            "validation_command": self.validation_command,
            "suggested_plugin": self.suggested_plugin,
            "body_chars": str(len(self.body)),
        }


def export_agtx_task(
    content: str,
    *,
    title: str,
    source_label: str = "(unspecified source)",
    validation_command: str = _DEFAULT_VALIDATION_COMMAND,
    suggested_plugin: str = "agtx",
    objective: Optional[str] = None,
    phases: Optional[Sequence[str]] = None,
    acceptance_criteria: Optional[Sequence[str]] = None,
    extra_sections: Optional[Dict[str, str]] = None,
) -> AgtxTask:
    """Render an AGTX task spec from a sprint doc / deliberation / report.

    The function is deterministic: identical inputs always produce
    byte-identical output. Section order is fixed (see
    :data:`_AGTX_SECTION_ORDER`) so consumers can grep for headers
    without pinning the producer version. Any provided ``extra_sections``
    appear after ``Lope Validation Requirements`` in insertion order.

    ``content`` is the source markdown that was the input to the
    export — it gets stored under ``Source`` for traceability. The
    ``objective`` / ``phases`` / ``acceptance_criteria`` parameters
    let callers supply pre-extracted structured slices when the raw
    content is too messy to embed verbatim. When omitted, the section
    bodies fall back to a single bullet pointing at the source.
    """

    safe_title = redact_text(title or "").strip() or "Untitled task"
    safe_source = redact_text(source_label or "").strip() or "(unspecified source)"
    safe_command = redact_text(validation_command or _DEFAULT_VALIDATION_COMMAND).strip()
    safe_plugin = redact_text(suggested_plugin or "agtx").strip() or "agtx"

    sections: Dict[str, str] = {
        "Source": (
            f"Generated by Lope v{_LOPE_VERSION} from `{safe_source}`."
        ),
        "Objective": _bulletize(
            objective,
            fallback=f"Translate the work captured in `{safe_source}` into "
            "an executable AGTX task while preserving every constraint "
            "and acceptance criterion produced by the council.",
        ),
        "Phases": _bullet_list(
            phases,
            fallback_lines=[
                "Inherit phase ordering from the source sprint.",
                "Run each phase under AGTX validator-in-the-loop.",
                "Block phase advancement on Lope rubric PASS.",
            ],
        ),
        "Acceptance Criteria": _bullet_list(
            acceptance_criteria,
            fallback_lines=[
                f"All sections of `{safe_source}` are addressed.",
                "Lope review on the resulting artifact returns no "
                "high-severity findings.",
                "AGTX execution log records every phase verdict.",
            ],
        ),
        "Suggested Plugin": safe_plugin,
        "Lope Validation Requirements": (
            f"Run `{safe_command}` after AGTX implementation. "
            "If a sprint doc is the source, also run `lope audit` against "
            "the AGTX execution log to surface phase-level dissent."
        ),
    }

    if extra_sections:
        for key, value in extra_sections.items():
            sections[redact_text(key).strip()] = redact_text(value or "").rstrip()

    body_parts: List[str] = [f"# AGTX Task: {safe_title}", ""]
    for header in list(_AGTX_SECTION_ORDER) + [
        h for h in sections.keys() if h not in _AGTX_SECTION_ORDER
    ]:
        if header not in sections:
            continue
        body_parts.append(f"## {header}")
        body_parts.append(sections[header].rstrip())
        body_parts.append("")

    body_parts.append("---")
    body_parts.append("")
    body_parts.append("### Source content snapshot")
    body_parts.append("```")
    body_parts.append(redact_text(content or "").rstrip())
    body_parts.append("```")

    body = "\n".join(body_parts).rstrip() + "\n"
    return AgtxTask(
        title=safe_title,
        body=body,
        source_label=safe_source,
        validation_command=safe_command,
        suggested_plugin=safe_plugin,
    )


def write_agtx_task(task: AgtxTask, target: Path) -> Path:
    """Write the rendered AGTX body to ``target``.

    Returns the path written so callers can echo it back to the user.
    """

    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(task.body, encoding="utf-8")
    return target


def _bulletize(value: Optional[str], *, fallback: str) -> str:
    body = redact_text(value or "").strip()
    if body:
        return body
    return f"- {redact_text(fallback).strip()}"


def _bullet_list(
    items: Optional[Iterable[str]],
    *,
    fallback_lines: Sequence[str],
) -> str:
    if items:
        cleaned = [redact_text(str(item)).strip() for item in items if str(item).strip()]
        if cleaned:
            return "\n".join(f"- {line}" for line in cleaned)
    return "\n".join(f"- {redact_text(line).strip()}" for line in fallback_lines)


# ---------------------------------------------------------------------------
# Review-report passthroughs
# ---------------------------------------------------------------------------


def export_markdown_pr(report: Any, *, include_raw: bool = False) -> str:
    """Render a consensus :class:`~lope.review.ReviewReport` as a PR comment.

    Thin wrapper around :func:`lope.review.render_report` so callers
    have a single entry point for "I want every export shape lope can
    produce". The Phase 3 renderer already redacts its output.
    """

    from .review import render_report

    return render_report(report, output_format="markdown-pr", include_raw=include_raw)


def export_sarif(report: Any) -> str:
    """Render a consensus report as SARIF v2.1.0 JSON."""

    from .review import render_report

    return render_report(report, output_format="sarif")


__all__ = [
    "AgtxTask",
    "export_agtx_task",
    "export_markdown_pr",
    "export_sarif",
    "write_agtx_task",
]
